FROM openjdk:17.0.2
LABEL authors="Matias Figueroa"

WORKDIR /app/msvc-usuarios

COPY ./msvc-usuarios/.mvn ./.mvn
COPY ./msvc-usuarios/mvnw .
COPY ./msvc-usuarios/pom.xml .

RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/

COPY ./msvc-usuarios/src ./src

RUN ./mvnw clean package -DskipTests

EXPOSE 8001

CMD ["java", "-jar", "./target/msvc-usuarios-0.0.1-SNAPSHOT.jar"]